name: Home
version: 1.0.2
main: net.testusuke.open.Home.Main
author: testusuke
website: https://testusuke.net
description: コンフィグオンリーのホームプラグイン /home help
commands:
  pghome:
    description: ホームプラグインを使用するための基本的なコマンドです。
  pgsethome:
    description: ホームを設定するためのコマンドです。